### ISSUE TITLE
Issue for review

### ISSUE THREAD

**Issue by CaptainBawa** [CaptainBawa/Recipe-App#11]
Kanban Board Link: https://github.com/users/CaptainBawa/projects/1/views/1

### We are two:

- [ ] @CaptainBawa - Member 2
- [ ] @mahabubx7 - Member 1

**Comment by DammyShittu** [comment]
Hi @CaptainBawa and @mahabubx7,

## Highlights
✔️ Assigned tasks

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] Kindly add these two missing tasks.

  ![image](https://github.com/CaptainBawa/Recipe-App/assets/54848363/9211e46c-8503-49b6-8cd4-f01fc955e58e)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by muneebulrehman** [comment]
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- Added tasks requested by the previous reviewer
- Good follow-up with the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
